name: SpectraWallet
options:
  projectFormat: xcode15_3
  bundleIdPrefix: com.renz
  deploymentTarget:
    iOS: '16.0'
settings:
  base:
    SWIFT_VERSION: '5.0'
    TARGETED_DEVICE_FAMILY: '1'
targets:
  SpectraWallet:
    type: application
    platform: iOS
    sources: [SpectraWallet]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.renz.spectrawallet
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Phantom
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MARKETING_VERSION: '1.4'
        CURRENT_PROJECT_VERSION: '5'
    scheme: {}
