import Foundation

var wallet = WalletData()
assert(wallet.total == 0)
assert(!wallet.add(coin: "SOL", units: -1))
assert(!wallet.add(coin: "SOL", units: .nan))
assert(!wallet.add(coin: "SOL", units: .infinity))
assert(!wallet.add(coin: "OTHER", units: 1))
assert(!wallet.add(coin: "SOL", units: 0))
assert(wallet.add(coin: "SOL", units: 2))
assert(wallet.total == 300)
assert(wallet.add(coin: "USDC", units: 50))
assert(wallet.total == 350)
assert(wallet.entries.count == 2)
let data = try JSONEncoder().encode(wallet)
let restored = WalletData.restored(data)
assert(restored.total == 350 && restored.entries.count == 2)
assert(WalletData.restored(Data("invalid".utf8)).total == 0)
assert(!wallet.add(coin: "BTC", units: 1_000_000_000))
assert(wallet.total == 350)
for _ in 0..<120 { assert(wallet.add(coin: "USDC", units: 1)) }
assert(wallet.entries.count == 100)
assert(wallet.total == 470)
print("Balance validation, persistence round-trip, cap, and history checks passed.")
