import Foundation

var wallet = WalletData()
assert(wallet.total == 0)
assert(!wallet.add(coin: "SOL", units: -1))
assert(!wallet.add(coin: "SOL", units: .nan))
assert(!wallet.add(coin: "SOL", units: .infinity))
assert(!wallet.add(coin: "OTHER", units: 1))
assert(!wallet.add(coin: "SOL", units: 0))
assert(wallet.add(coin: "SOL", units: 2))
assert(wallet.total == 300)
assert(wallet.add(coin: "USDC", units: 50))
assert(wallet.total == 350)
assert(wallet.entries.count == 2)
let data = try JSONEncoder().encode(wallet)
let restored = WalletData.restored(data)
assert(restored.total == 350 && restored.entries.count == 2)
assert(WalletData.restored(Data("invalid".utf8)).total == 0)
assert(!wallet.add(coin: "BTC", units: 1_000_000_000))
assert(wallet.total == 350)
for _ in 0..<120 { assert(wallet.add(coin: "USDC", units: 1)) }
assert(wallet.entries.count == 100)
assert(wallet.total == 470)
print("Balance validation, persistence round-trip, cap, and history checks passed.")

var trading = WalletData()
assert(!trading.addCash(.infinity))
assert(!trading.addCash(-1))
assert(trading.addCash(100))
assert(trading.cashBalance == 100 && trading.total == 100)
assert(!trading.buy(coin: "SOL", dollars: 101))
assert(!trading.buy(coin: "INVALID", dollars: 10))
assert(trading.buy(coin: "SOL", dollars: 75))
assert(trading.cashBalance == 25 && trading.balances["SOL"] == 0.5)
assert(abs(trading.total - 100) < 0.000001)
assert(!trading.send(coin: "SOL", units: 0.6, recipient: "Friend"))
assert(!trading.send(coin: "SOL", units: 0.1, recipient: "  "))
assert(!trading.send(coin: "SOL", units: .nan, recipient: "Friend"))
assert(trading.send(coin: "SOL", units: 0.1, recipient: "Friend"))
assert(abs(trading.total - 85) < 0.000001)
assert(trading.entries.first?.kind == "send" && trading.entries.first?.units == -0.1)
let tradingCopy = WalletData.restored(try JSONEncoder().encode(trading))
assert(tradingCopy.cashBalance == 25 && tradingCopy.entries.first?.note == "Friend")
let legacy = Data("{\"name\":\"Legacy\",\"balances\":{\"SOL\":2},\"entries\":[{\"id\":\"12345678-1234-1234-1234-123456789012\",\"coin\":\"SOL\",\"units\":2,\"date\":0}]}".utf8)
let migrated = WalletData.restored(legacy)
assert(migrated.name == "Legacy" && migrated.total == 300 && migrated.cashBalance == 0)
assert(migrated.entries.count == 1 && migrated.entries.first?.kind == nil)
assert(WalletData.restored(Data("{\"name\":\"Bad\",\"balances\":{},\"entries\":[],\"cash\":-1}".utf8)).cashBalance == 0)
print("Cash, buy/send, rejection, persistence and legacy migration checks passed.")
